// packages/brand-svelte/src/lib/components/data-table.svelte
<!--
  A table of facts: providers, feature flags, templates. Built on
  shadcn-svelte's Table. accent: boxed, with one column in a soft orange
  wash, for landing and product pages. lines: a strong line under the
  headings and thin lines between rows, for docs.
-->
<script lang="ts">
	import { cn } from "$brand/utils.js";
	import type { Snippet } from "svelte";
	import * as Table from "$brand/ui/table/index.js";

	let {
		columns,
		rows,
		variant = "accent",
		/** How many columns from the left hold names: text color, on one line. */
		names = 1,
		/** The column that matters, washed in orange in the accent style. The last one by default. */
		accent: accentColumn,
		class: className,
	}: {
		columns: (Snippet | string)[];
		rows: (Snippet | string)[][];
		variant?: "accent" | "lines";
		names?: number;
		accent?: number;
		class?: string;
	} = $props();

	const accent = $derived(variant === "accent");
	const washed = $derived(accentColumn ?? columns.length - 1);
</script>

<div data-slot="data-table" class={cn(accent && "overflow-hidden rounded-xl border", className)}>
	<Table.Root class="text-[0.84rem]">
		<Table.Header class={cn(!accent && "[&_tr]:border-foreground")}>
			<Table.Row class="hover:bg-transparent">
				{#each columns as c, i (i)}
					<Table.Head class={cn("h-auto py-2.5 font-medium text-foreground", accent ? "px-4" : "px-3", accent && i === washed && "bg-primary/7 text-primary")}>
						{#if typeof c === "string"}{c}{:else}{@render c()}{/if}
					</Table.Head>
				{/each}
			</Table.Row>
		</Table.Header>
		<Table.Body>
			{#each rows as row, r (r)}
				<Table.Row class="hover:bg-transparent">
					{#each row as cell, i (i)}
						<Table.Cell
							class={cn(
								"py-3 align-top leading-relaxed",
								accent ? "px-4" : "px-3",
								accent && i === washed && "bg-primary/7",
								i < names ? "whitespace-nowrap text-foreground" : "min-w-36 whitespace-normal text-muted-foreground",
							)}
						>
							{#if typeof cell === "string"}{cell}{:else}{@render cell()}{/if}
						</Table.Cell>
					{/each}
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</div>

// src/components/brand/data-table.tsx
import type { ReactNode } from "react"
import { cn } from "cn"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

type DataTableProps = {
  columns: ReactNode[]
  rows: ReactNode[][]
  /**
   * accent: boxed, with the last column in a soft orange wash, for tables on
   * landing and product pages. lines: a strong line under the headings and
   * thin lines between rows, for docs.
   */
  variant?: "accent" | "lines"
  /** How many columns from the left hold names: text color, on one line. */
  names?: number
  className?: string
}

/** A table of facts: providers, feature flags, templates. Built on shadcn's Table. */
export function DataTable({ columns, rows, variant = "accent", names = 1, className }: DataTableProps) {
  const accent = variant === "accent"
  return (
    <div data-slot="data-table" className={cn(accent && "overflow-hidden rounded-xl border", className)}>
      <Table className="text-[0.84rem]">
        <TableHeader className={cn(!accent && "[&_tr]:border-foreground")}>
          <TableRow className="hover:bg-transparent">
            {columns.map((c, i) => (
              <TableHead key={i} className={cn("h-auto py-2.5 font-medium text-foreground", accent ? "px-4 last:bg-primary/7 last:text-primary" : "px-3")}>
                {c}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((row, r) => (
            <TableRow key={r} className="hover:bg-transparent">
              {row.map((cell, i) => (
                <TableCell
                  key={i}
                  className={cn(
                    "py-3 align-top leading-relaxed",
                    accent ? "px-4 last:bg-primary/7" : "px-3",
                    i < names ? "whitespace-nowrap text-foreground" : "whitespace-normal text-muted-foreground",
                  )}
                >
                  {cell}
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
