// boilerplates/svelte-app/src/routes/about/+page.svelte
<script lang="ts">
	// The about page, which needs no block of its own: PageIntro, prose,
	// outline cards, the real command with what it does, big numbers and the
	// author in an outline card (docs/content-blocks.md). The words are example
	// copy.
	import { siGithub } from 'simple-icons';
	import SiteHead from '$brand/blocks/site/site-head.svelte';
	import Container from '$brand/blocks/site/container.svelte';
	import PageIntro from '$brand/blocks/site/page-intro.svelte';
	import Section from '$brand/blocks/site/section.svelte';
	import Prose from '$brand/blocks/site/prose.svelte';
	import BigNumbers from '$brand/blocks/site/big-numbers.svelte';
	import CtaBand from '$brand/blocks/site/cta-band.svelte';
	import ButtonLink from '$brand/blocks/site/button-link.svelte';
	import CommandBar from '$brand/components/command-bar.svelte';
	import StepNumber from '$brand/components/step-number.svelte';
	import Mark from '$brand/components/mark.svelte';
	import BrandIcon from '$brand/components/brand-icon.svelte';
	import SiteShell from '$brand/blocks/site/site-shell.svelte';
	import { Card } from '$brand/ui/card/index.js';
	import ThemeToggle from '$lib/theme-toggle.svelte';

	// Example content, in the shape the lab's about page uses.
	const principles = [
		['Zero magic', 'Example copy: one line on a principle. Everything is a file you can open.'],
		['Native passthrough', 'Example copy: whatever you wrap keeps working exactly as it did.'],
		['Templates over docs', 'Example copy: the right defaults, drop a key in and go.'],
		['Reversible everything', 'Example copy: rename before delete, back up before rename.']
	];

	const howItWorks = [
		'Example copy: the first thing that happens when you run the command.',
		'Example copy: the second thing, in the order it happens.',
		'Example copy: the third thing, and what you end up with.',
		'Example copy: the last thing, which is usually a symlink.'
	];

	const glance: readonly (readonly [value: string, label: string])[] = [
		['0.4.0', 'Current version'],
		['5', 'Releases shipped'],
		['MIT', 'License'],
		['4', 'Platforms']
	];
</script>

<SiteShell site="example" maker="by hmziq" nav={['Projects', 'How it works', 'About']} current="About">
	{#snippet extra()}<ThemeToggle />{/snippet}
	{#snippet children()}
		<SiteHead
			site="freeoxide"
			title="About — svelte-app"
			description="Why this exists and who is behind it. Example content."
			url="https://example.com/about"
		/>

		<Container>
			<PageIntro>
				{#snippet kicker()}About{/snippet}
				{#snippet title()}About the example{/snippet}
				{#snippet lede()}Example copy: one sentence on what this is and who it is for, written to be replaced.{/snippet}
			</PageIntro>
		</Container>

		<Section>
			{#snippet title()}Why it exists{/snippet}
			{#snippet intro()}The problem, in the lab's words. Example copy.{/snippet}
			<Prose class="max-w-2xl">
				{#snippet children()}
					<p>Example copy: two or three paragraphs on the problem this solves. Replace every word with the project's own.</p>
					<p>Example copy: the second paragraph. Say plainly what the tool does about it.</p>
				{/snippet}
			</Prose>
		</Section>

		<Section>
			{#snippet title()}What I optimize for{/snippet}
			{#snippet intro()}The principles. Example copy.{/snippet}
			<div class="grid gap-4 md:grid-cols-2">
				{#each principles as [title, body] (title)}
					<Card class="gap-3 bg-transparent px-6 shadow-none">
						{#snippet children()}
							<h3 class="text-[1.0625rem] font-medium">{title}</h3>
							<p class="text-[0.9rem] leading-relaxed text-muted-foreground">{body}</p>
						{/snippet}
					</Card>
				{/each}
			</div>
		</Section>

		<Section>
			{#snippet title()}How it works{/snippet}
			{#snippet intro()}Example copy: when you run the command below, four things happen.{/snippet}
			<div class="flex flex-col gap-5">
				<!-- An example to read, not to paste: no copy button. -->
				<CommandBar command="example run --once" copy={false} />
				<ol class="grid max-w-[52rem] gap-3">
					{#each howItWorks as text, i (i)}
						<li class="grid grid-cols-[2.25rem_minmax(0,1fr)] items-start gap-4">
							<StepNumber n={i + 1} done />
							<p class="pt-1.5 text-[0.9375rem] leading-relaxed">{text}</p>
						</li>
					{/each}
				</ol>
				<p class="mt-1 max-w-2xl leading-relaxed text-muted-foreground">Example copy: the closing line under the steps.</p>
			</div>
		</Section>

		<Section>
			{#snippet title()}At a glance{/snippet}
			<BigNumbers items={glance} />
		</Section>

		<Section>
			{#snippet title()}Built by hmziqrs{/snippet}
			<Card class="max-w-3xl flex-row items-start gap-6 bg-transparent px-6 shadow-none sm:px-9 sm:py-9">
				{#snippet children()}
					<Mark symbol="Hq" size={64} />
					<div class="flex flex-col gap-3">
						<h3 class="text-xl font-medium">Built by hmziqrs</h3>
						<p class="text-[0.9375rem] leading-relaxed text-muted-foreground">Example copy: who is behind this, in their own words.</p>
						<div class="flex flex-wrap gap-2">
							<ButtonLink href="https://github.com" variant="outline" size="sm">
								<BrandIcon icon={siGithub} data-icon="inline-start" />
								Source on GitHub
							</ButtonLink>
							<ButtonLink href="/" variant="outline" size="sm">hmziq.rs</ButtonLink>
							<ButtonLink href="/changelog" variant="outline" size="sm">See releases</ButtonLink>
						</div>
					</div>
				{/snippet}
			</Card>
		</Section>

		<CtaBand title="Ready to try it?">
			{#snippet body()}Example copy: one command, and you are running.{/snippet}
			{#snippet actions()}
				<ButtonLink href="/docs/installation" size="lg" class="px-5">Get started</ButtonLink>
				<ButtonLink href="/blog" size="lg" variant="outline" class="px-5">Read the blog</ButtonLink>
			{/snippet}
		</CtaBand>
	{/snippet}
</SiteShell>

// apps/lab/src/sites/claude-multi/about.tsx
import { siGithub } from "simple-icons"
import { BrandIcon } from "@/components/brand/brand-icon"
import { CommandBar } from "@/components/brand/command"
import { StepNumber } from "@/components/brand/stepper"
import { Mark } from "@/components/brand/wordmark"
import { Card } from "@/components/ui/card"
import { BigNumbers, Prose } from "../shared/content"
import { ButtonLink, Container, CtaBand, PageIntro, Section } from "../shared/site"
import { ClaudeMultiShell } from "./blocks"
import { glance, howItWorks, principles } from "./data"

/** claude-multi.hmziq.xyz/about */
export function ClaudeMultiAbout() {
  return (
    <ClaudeMultiShell current="About">
      <Container>
        <PageIntro
          kicker="About"
          title={
            <>
              About <span className="whitespace-nowrap">claude-multi</span>
            </>
          }
          lede="claude-multi is a CLI that runs multiple Claude Code instances side by side. Each one talks to a different AI provider and keeps its own config directory."
        />
      </Container>

      <Section title="A config directory is a single shared state" intro="Why it exists.">
        <Prose className="max-w-2xl">
          <p>
            Claude Code stores everything in ~/.claude: settings, MCP servers, plugins, skills, history. Try a second model and that one directory becomes a problem. I ended up editing settings by hand, swapping keys, and keeping shell aliases nobody asked for. Sessions and context get overwritten and you find out later.
          </p>
          <p>
            claude-multi gives every provider its own alias and config directory. One alias per provider (claude-glm, claude-deepseek, claude-anthropic), each rooted under ~/.claude-multi/. Plugins and skills symlink from your primary install, so you still maintain them in one place.
          </p>
          <p>
            There are no daemons and no background services. Nothing phones home. Every instance is a real directory you can cd into and inspect with the tools you already use.
          </p>
        </Prose>
      </Section>

      <Section title="What I optimize for" intro="The principles.">
        <div className="grid gap-4 md:grid-cols-2">
          {principles.map(([title, body]) => (
            <Card key={title} className="gap-3 bg-transparent px-6 shadow-none">
              <h3 className="text-[1.0625rem] font-medium">{title}</h3>
              <p className="text-[0.9rem] leading-relaxed text-muted-foreground">{body}</p>
            </Card>
          ))}
        </div>
      </Section>

      <Section title="A wrapper, not a fork" intro="When you run claude-multi add glm --provider glm, four things happen.">
        <div className="flex flex-col gap-5">
          {/* An example to read, not to paste: no copy button. */}
          <CommandBar command="claude-multi add glm --provider glm" copy={false} />
          <ol className="grid max-w-[52rem] gap-3">
            {howItWorks.map((text, i) => (
              <li key={i} className="grid grid-cols-[2.25rem_minmax(0,1fr)] items-start gap-4">
                <StepNumber n={i + 1} done />
                <p className="pt-1.5 text-[0.9375rem] leading-relaxed">{text}</p>
              </li>
            ))}
          </ol>
          <p className="mt-1 max-w-2xl leading-relaxed text-muted-foreground">
            That's the whole trick. One environment variable pointing at a config directory, plus a few symlinks. Nothing proxies your traffic and nothing patches the binary.
          </p>
        </div>
      </Section>

      <Section title="At a glance">
        <BigNumbers items={glance} />
      </Section>

      <Section title="Built by hmziqrs">
        <Card className="max-w-3xl flex-row items-start gap-6 bg-transparent px-6 shadow-none sm:px-9 sm:py-9">
          <Mark symbol="Hq" size={64} />
          <div className="flex flex-col gap-3">
            <h3 className="text-xl font-medium">Built by hmziqrs</h3>
            <p className="text-[0.9375rem] leading-relaxed text-muted-foreground">
              I'm an independent developer and I build open-source tooling for my own workflow first. claude-multi exists because switching providers halfway through a day kept breaking my setup, and every alternative meant learning a new CLI I did not want to learn.
            </p>
            <div className="flex flex-wrap gap-2">
              <ButtonLink href="#" variant="outline" size="sm">
                <BrandIcon icon={siGithub} data-icon="inline-start" />
                Source on GitHub
              </ButtonLink>
              <ButtonLink href="#" variant="outline" size="sm">
                hmziq.rs
              </ButtonLink>
              <ButtonLink href="#" variant="outline" size="sm">
                See releases
              </ButtonLink>
            </div>
          </div>
        </Card>
      </Section>

      <CtaBand
        title="Ready to try it?"
        body="One npm install, two commands, and you have your first provider running."
        actions={
          <>
            <ButtonLink href="#" size="lg" className="px-5">
              Get started
            </ButtonLink>
            <ButtonLink href="#" size="lg" variant="outline" className="px-5">
              Browse providers
            </ButtonLink>
          </>
        }
      />
    </ClaudeMultiShell>
  )
}
