// src/sites/claude-multi/not-found.tsx
import { Rings } from "@/components/brand/rings"
import { ButtonLink, Container, PageIntro } from "../shared/site"
import { ClaudeMultiShell } from "./blocks"

/** claude-multi's 404: the words, and rings drawn from "not found" beside them. */
export function ClaudeMultiNotFound() {
  return (
    <ClaudeMultiShell layout="page" mainClassName="pb-24">
      <Container>
        <div className="grid min-h-88 items-center gap-8 md:grid-cols-2">
          <PageIntro kicker="404" title="Page not found" lede="This URL doesn't point to anything. The page probably moved, or the link was wrong.">
            <div className="flex flex-wrap gap-3">
              <ButtonLink href="#" size="lg" className="px-5">
                Back to home
              </ButtonLink>
              <ButtonLink href="#" size="lg" variant="outline" className="px-5">
                Read the docs
              </ButtonLink>
            </div>
          </PageIntro>
          <Rings seed="not found" label="Rings, one of them orange" />
        </div>
      </Container>
    </ClaudeMultiShell>
  )
}

// packages/brand-svelte/src/lib/blocks/content/not-found.svelte
<!--
  The 404 (the lab's not-found page): the words on the left, and rings
  drawn from "not found" beside them. What went wrong and the way out
  arrive as props, so the same block covers a missing page and a page that
  failed to draw.
-->
<script lang="ts">
	import Container from "$brand/blocks/site/container.svelte";
	import PageIntro from "$brand/blocks/site/page-intro.svelte";
	import Rings from "$brand/components/rings.svelte";

	let {
		/** The status, shown as the small word above the title. */
		status = "404",
		/** The next two are renamed here because the snippets that carry them
		 * into the page intro are also called `title` and `lede`, and a
		 * snippet's name shadows everything inside it. */
		title: titleText,
		lede: ledeText,
		/** The rings' seed. "not found" by default. */
		seed = "not found",
		class: className,
		children: actions,
	}: { status?: string; title: string; lede: string; seed?: string; class?: string; children: import("svelte").Snippet } = $props();
</script>

<Container class={className}>
	<div class="grid min-h-88 items-center gap-8 md:grid-cols-2">
		<PageIntro>
			{#snippet kicker()}
				{status}
			{/snippet}
			{#snippet title()}
				{titleText}
			{/snippet}
			{#snippet lede()}
				{ledeText}
			{/snippet}
			{#snippet children()}
				<div class="flex flex-wrap gap-3">
					{@render actions()}
				</div>
			{/snippet}
		</PageIntro>
		<Rings {seed} label="Rings, one of them orange" />
	</div>
</Container>
